image: reactnativecommunity/react-native-android

pipelines:
  default:
    - step:
        name: Install and Build
        caches:
          - node
        size: 2x # Use a larger container for this step.
        script:
          - ./build.sh
