image: reactnativecommunity/react-native-android

pipelines:
  default:
    - step:
        name: Install and Build
        script:
          - echo "Non 'release' commit, no build sequence will be activated."
  tags:
    release/*:
      - step:
          name: Install and Build on Release Tag
          caches:
            - node
          size: 2x
          script:
            - ./build.sh
