image: reactnativecommunity/react-native-android

pipelines:
  default:
    - step:
        name: Install and Build
        caches:
          - node
        size: 2x # Use a larger container for this step.
        script:
          - echo "This will run on every push except for the 'release' branch"
  branches:
    release:
      - step:
          name: Install and Build on Release
          caches:
            - node
          size: 2x
          script:
            - ./build.sh
